### ISSUE TITLE
Channel List bug.

### ISSUE THREAD

**Issue by ConniBug** [The-name-Tranquility-is-already-taken/TranqulityFrontend#6]
Channel List not rendering in correct position.

[Example](https://cdn.discordapp.com/attachments/825762603405672508/828353047087808592/unknown.png)

**Comment by altered-beast** [comment]
fixed in [commit](https://github.com/The-name-Tranquility-is-already-taken/TranqulityFrontend/commit/f878f2ddd3582ca7a996b93ce9faa09f94ffca35) hail satan
